name := "scala-service"
version := "0.1"
scalaVersion := "2.13.12"
libraryDependencies += "com.typesafe.akka" %% "akka-http" % "10.2.10"
libraryDependencies += "com.typesafe.akka" %% "akka-stream" % "2.6.20"
