source 'https://rubygems.org'
ruby '3.3.0'

gem 'rails', '~> 7.2'
gem 'puma', '>= 5.0'
gem 'pg', '~> 1.5'
gem 'activeadmin', '~> 3.2'
gem 'devise', '~> 4.9'
gem 'bootsnap', require: false
gem 'tzinfo-data', platforms: %i[ windows jruby ]

group :development do
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
end

group :test do
  gem 'rspec-rails', '~> 7.0'
end
