# frozen_string_literal: true

source 'https://rubygems.org'
ruby '~> 3.3.0'

gem 'activeadmin', '~> 3.2'
gem 'bootsnap', require: false
gem 'devise', '~> 5.0', '>= 5.0.4'
gem 'pg', '~> 1.5'
gem 'puma', '>= 5.0'
gem 'rails', '~> 7.2', '>= 7.2.3.1'
gem 'sprockets-rails', '~> 3.5'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development do
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
end

group :test do
  gem 'rspec-rails', '~> 7.0'
end
